// This code was generated by a tool
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated

abstract class EnvConfig {
  String get facebookAppId;
  String get fbLoginProtocolScheme;
  String get googleLoginProtocolScheme;
  String get googleMapsApiKey;
  int get someInt;
  double get someDecimalNumber;
}


class EnvConfigImpl extends EnvConfig {
  @override String get facebookAppId => '421720451234247';
  @override String get fbLoginProtocolScheme => 'fb421720451234247';
  @override String get googleLoginProtocolScheme => 'com.googleusercontent.apps.1234567812345678-je55jt95q7uc15fme0fudb87vvipnftevvro';
  @override String get googleMapsApiKey => 'BIzaSyAAbir5DAWT_lomin25RkUzxcvb123yCnDEG';
  @override int get someInt => 123;
  @override double get someDecimalNumber => 126.45;
}


