// This code was generated by a tool
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated

class EnvConfig {
  String get facebookAppId => '421720451234247';
  String get fbLoginProtocolScheme => 'fb421720451234247';
  String get googleLoginProtocolScheme => 'com.googleusercontent.apps.1234567812345678-je55jt95q7uc15fme0fudb87vvipnftevvro';
  String get googleMapsApiKey => 'BIzaSyAAbir5DAWT_lomin25RkUzxcvb123yCnDEG';
}


