// This code was generated by a tool
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated

import android.content.Context
import android.content.res.Resources
import com.example.example.R

class EnvConfig(context: Context) {
    private val resources: Resources = context.resources

    val facebookAppId: String get() = resources.getString(R.string.facebook_app_id)
    val fbLoginProtocolScheme: String get() = resources.getString(R.string.fb_login_protocol_scheme)
    val googleLoginProtocolScheme: String get() = resources.getString(R.string.google_login_protocol_scheme)
    val googleMapsApiKey: String get() = resources.getString(R.string.google_maps_api_key)
}


